### ISSUE TITLE
suport kicad8 and grbl cnc ?

### ISSUE THREAD

**Issue by Witawat** [adarwoo/kicad2gcode#1]
suport kicad8 and grbl cnc ?

**Comment by adarwoo** [comment]
GRBL CNCs should be supported, but requing to write the custom layer.
KiCAD 8 is already supported - but - KiCAD is planning on removing the Swig based Python layer that this is using.
A new approach is planned, annonced, but not release yet.
I am putting further development on hold until this new API if officially released by KiCAD.
